name: cas-adapter:Build & Promote Image to Dev

on:
  workflow_dispatch:

env:
  OPENSHIFT_REGISTRY: ${{ secrets.OPENSHIFT_REGISTRY }}
  OPENSHIFT_URL: ${{ secrets.OPENSHIFT_URL }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  BUILD_TAG: latest
  TARGET_TAG: dev

jobs:
  promote-to-prod:
    name: Promote Latest to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Debug - Print Important Env Variables
        run: |
          echo " Registry: $OPENSHIFT_REGISTRY"
          echo " Namespace: $OPENSHIFT_NAMESPACE"
          echo " Image Name: $IMAGE_NAME"
          echo " Build Tag: $BUILD_TAG"
          echo " Target Tag: $TARGET_TAG"

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OpenShift Internal Registry
        run: |
          echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login -u unused --password-stdin ${{ env.OPENSHIFT_REGISTRY }}

      - name: Build and Push Image (only latest)
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            -t $OPENSHIFT_REGISTRY/$OPENSHIFT_NAMESPACE/$IMAGE_NAME:$BUILD_TAG \
            .

      - name: Install oc CLI
        uses: redhat-actions/oc-installer@v1

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true

      #- name: Promote Image from latest to dev
        #run: |
          #oc tag $OPENSHIFT_NAMESPACE/$IMAGE_NAME:$BUILD_TAG $OPENSHIFT_NAMESPACE/$IMAGE_NAME:$TARGET_TAG
