name: Build on GitHub & Push to OpenShift

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: cas-adapter
  REGISTRY: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_NAMESPACE }}
  TAG: dev

jobs:
  build:
    name: Build Image
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DEBUG
        run: echo "REGISTRY ${{ secrets.OPENSHIFT_REGISTRY }} USERNAME ${{ secrets.DOCKER_USERNAME }}" 

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.OPENSHIFT_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Login to Registry
      #   run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin $REGISTRY

      - name: Build to Docker image
        uses: docker/build-push-action@v6
        with:
          # push: true
          #context: ./app
          tags: |
            ${{ env.APP_NAME }}:latest

      - name: Tag Image
        run:  docker tag $APP_NAME:latest $REGISTRY/$APP_NAME:latest

      - name: Push Image
        run:  docker push $REGISTRY/$APP_NAME:latest