name: Promote to Prod

on:
  workflow_dispatch:

env:
  IMAGE_NAME: cas-adapter
  IMAGE_REGISTRY: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}
  IMAGE_CURRENT_ENV_TAG: test
  IMAGE_PROMOTE_ENV_TAG: prod
  IMAGE_PROMOTE_ENV_BACKUP_TAG: prod-backup

jobs:
  promote-cas-adapter-test:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'

    steps:
      
      - name: Promote cas-adapter to test
        uses: tinact/docker.image-retag@master
        with:
          image_name: ${{ env.IMAGE_NAME }}
          image_old_tag: ${{ env.IMAGE_CURRENT_ENV_TAG }}
          image_new_tag: ${{ env.IMAGE_PROMOTE_ENV_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          registry_username: ${{ secrets.OCP4_USERNAME }}
          registry_password: ${{ secrets.OPENSHIFT_TOKEN }}
          
